name: Deploy to Firebase
  # You may pin to the exact commit or the version.
  # uses: lowply/deploy-firebase@2d5ea962add04eb6fe1c17dd1dafffc806bdfe8a

on: 
 push:
    branches: 
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build:prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
